name: lexigo-dev

services:
  postgres:
    container_name: lexigo-dev-postgres
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lexigo
    ports:
      - "5500:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lexigo-network-dev

  redis:
    container_name: lexigo-dev-redis
    image: redis:8.4-alpine
    ports:
      - "6600:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lexigo-network-dev

  backend:
    container_name: lexigo-dev-backend
    build:
      context: ../..
      dockerfile: deploy/docker/backend/Dockerfile.dev
    ports:
      - "8800:8080"
    env_file:
      - ../env/dev/backend.env
    volumes:
      - ../../backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lexigo-network-dev

  frontend:
    container_name: lexigo-dev-frontend
    build:
      context: ../..
      dockerfile: deploy/docker/frontend/Dockerfile.dev
      args:
        ENV: dev
    ports:
      - "3300:5173"
    env_file:
      - ../env/dev/frontend.env
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - lexigo-network-dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  lexigo-network-dev:
    driver: bridge

