name: lexigo-prod

services:
  postgres:
    container_name: lexigo-prod-postgres
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lexigo
    ports:
      - "5501:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lexigo-network-prod

  redis:
    container_name: lexigo-prod-redis
    image: redis:8.4-alpine
    ports:
      - "6601:6379"
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lexigo-network-prod

  backend:
    container_name: lexigo-prod-backend
    build:
      context: ../..
      dockerfile: deploy/docker/backend/Dockerfile.prod
    ports:
      - "8801:8080"
    env_file:
      - ../env/prod/backend.env
    volumes:
      - ../../backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lexigo-network-prod

  frontend:
    container_name: lexigo-prod-frontend
    build:
      context: ../..
      dockerfile: deploy/docker/frontend/Dockerfile.prod
      args:
        ENV: prod
    ports:
      - "3301:80"
    env_file:
      - ../env/prod/frontend.env
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - lexigo-network-prod

volumes:
  postgres_data_prod:
  redis_data_prod:

networks:
  lexigo-network-prod:
    driver: bridge

